### ISSUE TITLE
rsitesearch does not yield the same results when enzymes are reversed

### ISSUE THREAD

**Issue by anoronh4** [GGFHF/ddRADseqTools#1]
I have found that reversing the enzymes that go into --enzyme1 and --enzyme2 significantly changes the number of fragments that are in the specified region. Is there a biological explanation for these results?

**Comment by fernandomoramarquez** [comment]
Hi,

First, we thanks you for your ddRADseqTools use. We attach a file with the explanation.

Regards

[Explanation.pdf](https://github.com/GGFHF/ddRADseqTools/files/833835/Explanation.pdf)

**Comment by anoronh4** [comment]
Thank you very much!
