### ISSUE TITLE
Using restriction site sequence instead of enzyme name, ERROR D301

### ISSUE THREAD

**Issue by hollisdahn** [GGFHF/ddRADseqTools#10]
Thanks a ton for writing this software. 

I'm trying to simulate digestions with different enzyme pairs on a reference genome with _rsitesearch.py_. It runs as expected for the default enzymes EcoRI and MseI. 
For some enzymes I want to try, the name is not recognized by the program nor is the restriction site sequence. Additionally, when I try replacing the names of the default enzymes with their restriction site sequence they are also not accepted, i.e. GAATTC for EcoRI and TTAA for MseI.

Any idea how I can fix this? Hopefully I'm missing something obvious!

`(base) C:\Users\Hollis\ddRADseqTools-master\Package>python rsitesearch.py --genfile=gen_ref.fna.gz --fragsfile=frags_out.fasta --enzyme1=EcoRI --enzyme2=TTAA
*** ERROR D301: Enzyme identification or restriction site sequence TTAA is not valid.

(base) C:\Users\Hollis\ddRADseqTools-master\Package>python rsitesearch.py --genfile=gen_ref.fna.gz --fragsfile=frags_out.fasta --enzyme1=SbfI --enzyme2=MspI
*** ERROR D301: Enzyme identification or restriction site sequence MspI is not valid.

(base) C:\Users\Hollis\ddRADseqTools-master\Package>python rsitesearch.py --genfile=gen_ref.fna.gz --fragsfile=frags_out.fasta --enzyme1=SbfI --enzyme2=CCGG
*** ERROR D301: Enzyme identification or restriction site sequence CCGG is not valid.

(base) C:\Users\Hollis\ddRADseqTools-master\Package>python rsitesearch.py --genfile=gen_ref.fna.gz --fragsfile=frags_out.fasta --enzyme1=EcoRI --enzyme2=MseI
The enzymes have different restriction site sequences, so the fragments will correspond to a double digestion.
Fragments written ...       667`

**Comment by fernandomoramarquez** [comment]
Dear "hollisdahn",

Thanks for using ddRADseqTools. 

We think that your problem is due to the cut site is not set in the restriction site sequence. The symbol used is "*". e.g., the sequence for EcoRI is G*AATTC. Can you please confirm that your problem is resolved with this change?

We will update the manual in the next version to clarify the use of sequences in the options "enzyme1" and "enzyme2".

All the best,
Unai and Fernando

**Comment by fernandomoramarquez** [comment]
Sorry, the symbol is "*" (asterisk) and the sequence  for EcoRI is G*AATTC.

**Comment by fernandomoramarquez** [comment]
Sorry, the "asterisk" is not shown when the mesage is sent. The sequence form EcoRI is G"asterisk"AATTC.

**Comment by hollisdahn** [comment]
That appears to have worked. It runs with restriction site sequences if I add an asterisk at the cut site.

Thanks!
