### ISSUE TITLE
seqlocation.py for cut sites

### ISSUE THREAD

**Issue by hollisdahn** [GGFHF/ddRADseqTools#11]
Hi again!

Hopefully a minor question, I get very different numbers if I use ddRADseqTools vs. SimRAD to find restriction sites in a given reference genome. The counts from seqlocation.py in ddRADseqTools are consistently about double the SimRAD numbers. Is this because seqlocation.py is also counting reverse compliments of the given restriction site sequence? Which count should I use in calculations for expected numbers of RAD loci?

e.g.:
(SbfI) ddRADseqtools: 336,076 restriction sites; SimRAD: 169,936 restriction sites
(EcoRI) ddRADseqtools: 2,182,576 restriction sites; SimRAD: 1,093,753 restriction sites

Thanks for the help last time.
-Hollis

**Comment by GGFHF** [comment]
Hi Hollis:

The seqlocation.py utility in ddRADseeqTools finds occurrences of a nucleotide sequence in both strands of the DNA and reports the locus, strand, start and end positions of each occurrence. If a sequence is palindromic, such as the restriction sites of EcoRI and SbfI, it will be found in equivalent positions of both strands.

If you need to determinate the number of RAD loci, it will be half of the found occurrences, what is the value that is reported by simRAD.
All the best,

Fernando and Unai
