### ISSUE TITLE
digesting with ambiguous recognition sites

### ISSUE THREAD

**Issue by anoronh4** [GGFHF/ddRADseqTools#2]
Hello again. First of all, thank you for helping on my last question. Now I am wondering, does your script handle enzymes that have more than one recognition site? For example, I want to double-digest using enzymes AvaII and MspI. AvaII has the recognition site G^GWCC, so right now to digest I have to do it twice. Is there any way to digest using these two enzymes in one step? I see that the program does not accept 3 enzymes and the restrictionsites.txt file does not accept ambiguous nucleotides. Is there another workaround I'm unaware of?

**Comment by GGFHF** [comment]
Hi again and thanks for your interest

this was an issue we had in mind when we designed the program, but we think there is no easy workaround here. In fact running the program twice will not result in accurate double digested fragment obtention (it will serve if you only wish to detect the cutting sites in a genome).
Hopefully, in the next version of ddRADseqTools, we'll try to improve the software to account for enzymes with more than one recognition site.

all the best!

Unai and Fernando

**Comment by anoronh4** [comment]
Unai and Fernando,

Thank you for your explanation. Could you let me know why running the program twice wouldn't work? For the first digest I have been using two recognition sites of the same enzyme and not setting a maximum fragment size (just a minimum size). Then, I take the resulting fragments.fasta and run the program on it with the remaining enzyme and min/max sizes. I'm not sure what the issue would be, at least in theory. 

Best, 
AMN

**Comment by GGFHF** [comment]
Hi again

we are not sure about the procedure you suggest. Could you submit us the parameter files you are running, so we can study this issue? 
Thanks in advance

Unai and Fernando

**Comment by edgardomortiz** [comment]
Hi, and thanks for developing this software, is what I was looking for since I need to do some ddRAD in silico.

I also think this feature is very important since there are many usable enzymes with degenerate sites (check this paper for example DOI 10.1186/s13007-016-0139-1). I wonder if the software is still being updated, I think you can use regular expressions to find all the alternative cutsites in the genome when you want to cut it with an enzyme with degenerate sites ( https://pythonforbiologists.com/regular-expressions/ ).

Best,
Edgardo

**Comment by fernandomoramarquez** [comment]
The new version 0.44 of ddRADseqTools is uploaded in GitHub. Now this software works with ambiguous restriction sites. Also both enzymes can be the same in rsiteseach.py, but no in others programs.

Regards,
Unai & Fernando
