### ISSUE TITLE
Does not work when both enzymes are the same

### ISSUE THREAD

**Issue by jpuritz** [GGFHF/ddRADseqTools#3]

**Comment by GGFHF** [comment]
Thanks for your input. No, this was designed for ddRADseq, not RADseq. In the near future, we will implement the analysis of enzymes in RADseq.  We will let you know.

**Comment by fernandomoramarquez** [comment]
The new version 0.44 of ddRADseqTools is uploaded in GitHub. Now this software works with ambiguous restriction sites. Also both enzymes can be the same in rsiteseach.py, but not in others programs.

Regards,
Unai & Fernando
