### ISSUE TITLE
Syntax Error in rsitesearch.py

### ISSUE THREAD

**Issue by kfergy** [GGFHF/ddRADseqTools#5]
Hey there,

When running the rsitesearch.py with all default settings except the genome file, I keep getting an error:

```
fergu003@Gregor:~/Tools/ddRADseqTools/Package$ python rsitesearch.py --genfile= file.fasta
  File "rsitesearch.py", line 66
    Message.print('info', 'The enzymes have different restriction site sequences, so the fragments will correspond to a double digestion.')
                ^
SyntaxError: invalid syntax
```

When I delete the lines in question, more keep coming up, all related to the message.print command. Still happens when --verbose=NO, and I'm not familiar enough with message.print or python to address the error. If this is on my end, just let me know and I'll bug someone in my office about it, but if it's in the script, any solutions?

Thanks,

Kim
[Ubuntu 16.04.3]

**Comment by fernandomoramarquez** [comment]
Hey Kim:

First, we thanks you for your ddRADseqTools use.

The ddRADseqTools software package needs Python3. Please run the next sentence:

python3 rsitesearch.py --genfile=file.fasta

or simply (if your working directory is where ddRADseqTools programs are):

./rsitesearch.py --genfile=file.fasta

Is your problem solved?

Regards,

**Comment by kfergy** [comment]
Sorry this reply took so long -- the computer I was using previously failed before I could try, and now I'm using a new server and got the same problem, to find I have already asked it! And indeed, adding "3" fixed everything. Sorry for such a simple question :)
