### ISSUE TITLE
Elaboration on simddradseq.py

### ISSUE THREAD

**Issue by bheimbu** [GGFHF/ddRADseqTools#7]
Hello,

I just encountered your software lately and would like to use the simulated paired-end reads by simddradseq.py for STACKS analyses. However, I am quite confused how barcodes are encoded. I have used 'individuals-5index1.txt', following '[ends.txt](https://github.com/GGFHF/ddRADseqTools/files/2410066/ends.txt)', and '[simddradseq-config.txt](https://github.com/GGFHF/ddRADseqTools/files/2410123/simddradseq-config.txt)'. Everything worked fine and I got the reads (for the fragments file. I've used my own draft termite genome).
But now, the problems began. When I want to use 'process_radtags' of STACKS, I don't know how to encode for the barcodes. 'process_radtags' cannot find any barcodes, though the reads are not demultiplexed accoding to the barcodes. 

Might it be due to the fastq headers of the simulated paired-end reads, as they contain no information about which one is the forward/reverse read?

Any help is highly appreciated,

Cheers Bastian

**Comment by bheimbu** [comment]
It's me again, Bastian,

I have another question concerning the simulated paired-end reads. Why are the barcode sequences in lower cases? Might this be the problem that 'process_radtags' cannot find any barcodes at all? 

Cheers Bastian

**Comment by GGFHF** [comment]
Hi Bastian,
thanks for using ddRADseqTools. Lower and upper cases can be used indistinctly in ddRADseqTools. We used lower cases to visually distinguish where the barcodes/DBRs and the restriction site motifs are located. Most of downstream analysis pipelines can handle lower cases in the sequences.
We think that the best choice to overcome the problems with STACKS would be to run indsdemultiplexing.py to demultiplex your individuals, and then, readstrim.py to remove the barcodes, so you can input the reads files in STACKS and follow the standard procedure. There are some examples of this in the bash scripts of the simulation-scripts directory of ddRADseqTools (for instance in simulation-pipeline-Bnapus-pe).
However, I found other RAD processing pipelines more user-friendly than STACKS. Particularly, we performed analysis with ddRADseqTools data with iPyrad, and they worked perfectly (even without previous barcode removal, and without demultiplexing).

Hope this helps, and don't hesitate to contact us if you have further problems with ddRADseqTools.

All the best,

Unai and Fernando

**Comment by bheimbu** [comment]
Thanks for your reply,

I am still wondering, why 'process_radtags' cannot find the barcode sequences? However, I had the same experience that STACKS is not really user-friendly. Though, I'll try iPyrad and see how it works. 

Cheers Bastian

**Comment by bheimbu** [comment]
Hi Unai and Fernando,

I've tried iPyrad with my simulated reads. It fails at step 1, because it cannot find any data for my individuals. I've used following files to create my reads: [simddradseq-config.txt](https://github.com/GGFHF/ddRADseqTools/files/2414380/simddradseq-config.txt), [ends.txt](https://github.com/GGFHF/ddRADseqTools/files/2414381/ends.txt), and [individuals-1index1-5index2.txt](https://github.com/GGFHF/ddRADseqTools/files/2414383/individuals-1index1-5index2.txt). For ipyrad, I have used following files: [params-simulated.txt](https://github.com/GGFHF/ddRADseqTools/files/2414389/params-simulated.txt) and [barcodes.txt](https://github.com/GGFHF/ddRADseqTools/files/2414391/barcodes.txt).

Any help is highly appreciated.


Cheers Bastian

**Comment by GGFHF** [comment]
Hi Bastian,

 I suggest to use the demultiplexer (indsdemultiplexing.py) and the trimmer (readstrim.py) implemented in ddRADseqTools, and then try to run iPyrad using the branching workflow approach (https://ipyrad.readthedocs.io/outline.html) skipping stages 1 (demultiplexing) and 2 (quality error filtering). In your simulated data, quality is average. That should work. In any case, we'll take a look to your parameter files to see if something's wrong.

We'll let you know,

Unai and Fernando

**Comment by bheimbu** [comment]
Thanks for your help,

I'll try with your suggestions and looking forward to your answer.


Cheers Bastian

**Comment by GGFHF** [comment]
Hi again,

 I realized that your barcodes.txt file does not fullfill iPyrad requirements. For ddRADseqTools, there are two indexes at the barcodes.txt file, while iPyrad seems to be able to handle only barcode files with the name of the individual and a single barcode (tab or space separated). Probably this produces an error in the first step of iPyrad that can be solved by using the strategy I mentioned in my past comment. Did it work?
Cheers 
Unai and Fernando

**Comment by GGFHF** [comment]
Hi Bastian, 
 were you able to run iPyrad following our advice? We'd appreciate some feedback.
All the best,
Unai and Fernando

**Comment by bheimbu** [comment]
Hi,

sorry for the late reply, I am on vacation this week. Anyway, I was able to run everything as I wanted.

Thanks for all your help,

Bastiab


Sent from my iPhone

On 1. Oct 2018, at 18:40, Grupo de Genética, Fisiología e Historia Forestal <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Bastian,
were you able to run iPyrad following our advice? We'd appreciate some feedback.
All the best,
Unai and Fernando
