### ISSUE TITLE
ERROR NOT-ZERO: This exception is not managed.

### ISSUE THREAD

**Issue by jdmontenegro** [GGFHF/ddRADseqTools#8]
Dear all,

Thank you for providing such a useful tool. I am trying to use it on a mammalian reference genome.
The first command run almost perfectly:
```
python3 rsitesearch.py --genfile=./genome.fa --fragsfile=./fragments.fa --enzyme1=PstI --enzyme2=MseI --fragstfile=fragments.stat
The enzymes have different restriction site sequences, so the fragments will correspond to a double digestion.
Fragments written ...    316802
The file fragments.fa containing the fragments of the double digest of the genome is created.
The statistics can be consulted in the file fragments.stat.
The CSV file fragments.csv can be used to import data in a statistics program.
The statistics graphic is saved in the file fragments.png.
The file Cporcellus_fragmets-GC-distribution.csv containing the GC distribution is created.
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_gtk3.py:197: Warning: Source ID 9 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
```
However, when I try to generate de library using the option:
```
"technique=IND1" I get an error:
*** ERROR NOT-ZERO: This exception is not managed.

```
Has this been tested before or is "IND1" just not available in the current version?

Look forward to hearing back from you.

Juan D. Montenegro

**Comment by fernandomoramarquez** [comment]
Dear Juan:

Thanks for using ddRADseqTools. The option "technique" is not used in rsitesearch.py. The options of this program can be shown running ./rsitesearch.py --help (see next image).

![rsitesearch_help](https://user-images.githubusercontent.com/13253102/58623306-fc0b0d00-82cd-11e9-9e00-161bbddff33e.jpg)

Regards,
Unai & Fernando

**Comment by jdmontenegro** [comment]
Dear Fernando,

Thank you for your response. I may not have explained myself clearly in my
email. After running the rsitesearch.py script I tried producing the
illumina library with the next command in the pipeline: simddradseq.py, any
option that is not the default in "technique" fails with the error I
mentioned before.

Would you be able to reproduce that error?

Cheers,

Juan D.

**Comment by fernandomoramarquez** [comment]
Dear Juan:

Can you please check if the options "dbrlen" and "index2len" are set 0 when you run simddradseq.py? If they are not passed as arguments in the command line, their values are taken from file "simddradseq-config.txt".

Cheers,
